### ISSUE TITLE
Error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by websashka** [ton-utils/reverse-proxy#2]
After 12 hour work:

**panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x67bcf8]**

```
goroutine 133 [running]:
github.com/xssnick/tonutils-go/adnl/dht.(*dhtNode).changeState(0xc0002a2b40, 0x0)
        /Users/xssnick/go/pkg/mod/github.com/xssnick/tonutils-go@v1.5.1-0.20230123133014-c4a895d57e23/adnl/dht/node.go:94 +0xb8
github.com/xssnick/tonutils-go/adnl/dht.(*dhtNode).checkPing(0xc0002a2b40, {0x7b7608, 0xc0024cfaa0})
        /Users/xssnick/go/pkg/mod/github.com/xssnick/tonutils-go@v1.5.1-0.20230123133014-c4a895d57e23/adnl/dht/node.go:310 +0x165
github.com/xssnick/tonutils-go/adnl/dht.(*dhtNode).poll(0xc0002a2b40)
        /Users/xssnick/go/pkg/mod/github.com/xssnick/tonutils-go@v1.5.1-0.20230123133014-c4a895d57e23/adnl/dht/node.go:356 +0x54
created by github.com/xssnick/tonutils-go/adnl/dht.connectToNode
        /Users/xssnick/go/pkg/mod/github.com/xssnick/tonutils-go@v1.5.1-0.20230123133014-c4a895d57e23/adnl/dht/node.go:62 +0x24a
 *  Terminal will be reused by tasks, press any key to close it. 
```

**Comment by xssnick** [comment]
Thank you for the report! Seems like a rare bug with closed DHT connection, will fix it soon.
